# Generated by Django 4.0.6 on 2022-07-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('desig', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='members_pics')),
            ],
        ),
    ]
